config/routes.rb
MarineLifeIdApp::Application.routes.draw do
  resources :guesses
  resources :identifications

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :images do
   collection do
     get :practice
     get :identify
     get :explore
   end
    resources :identifications, except: [:index]
    resources :guesses, except: [:index]
  end

  get 'animals/family'
  get 'animals/common'

  resources :identifications, only: [:index]

  root :to => 'images#index'

end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_filter :set_guess, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @guesses = Guess.all
    respond_with(@guesses)
    @image = Image.reviewed_images
  end

  def show
    respond_with(@guess)
  end

  def new
    @guess = Guess.new
    # respond_with(@guess)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guess }
    end
  end

  def edit
  end

  def create
    @image = Image.find(params[:image_id])
    @guess = @image.guesses.new(params[:guess])
    @guess.user_id = current_user.id

    respond_to do |format|
      if @guess.save
        format.html { redirect_to image_guesses_path, notice: 'Guess was successfully created.' }
        format.json { render json: @guess, status: :created, location: @guess }
      else
        format.html { render action: "new" }
        format.json { render json: @guess.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @guess.update_attributes(params[:guess])
    respond_with(@guess)
  end

  def destroy
    @guess.destroy
    respond_with(@guess)
  end
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/views/guesses/_form.html.erb
<%= form_for([@image, @guess]) do |f| %>
  <%= hidden_field_tag :image_id, @image.id %>

  <div class="field">
    <%= f.label :suborder %><br />
    <%= f.collection_select :suborder, Animal.select('DISTINCT(suborder)').order(:suborder), :suborder, :suborder, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :family %><br />
    <%= f.collection_select :family, [], :family, :family, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :common_name %><br />
    <%= f.collection_select :common_name, [], :id, :common_name, include_blank: true %>
  </div>

  <div class="actions" id="actions">
    <%= f.submit "guess!", class: "btn btn-default", id: "guess_button" %>
  </div>
<% end %>

app/views/guesses/edit.html.erb
<h1>Editing guess</h1>

<%= render 'form' %>

<%= link_to 'Show', @guess %> |
<%= link_to 'Back', guesses_path %>

app/views/guesses/index.html.erb
<h1>Listing guesses</h1>

<table>
  <tr>
    <th>Suborder</th>
    <th>Family</th>
    <th>Common name</th>
    <th>User</th>
    <th>Image</th>
    <th>Correct</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guesses.each do |guess| %>
  <tr>
    <td><%= guess.suborder %></td>
    <td><%= guess.family %></td>
    <td><%= guess.common_name %></td>
    <td><%= guess.user_id %></td>
    <td><%= guess.image_id %></td>
    <td><%= guess.correct %></td>
    <td><%= link_to 'Show', guess %></td>
    <td><%= link_to 'Edit', edit_guess_path(guess) %></td>
    <td><%= link_to 'Destroy', guess, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guess', new_guess_path %>

app/views/guesses/new.html.erb
<h1>New guess</h1>

<%= render 'form' %>

<%= link_to 'Back', guesses_path %>

app/views/guesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Suborder:</b>
  <%= @guess.suborder %>
</p>

<p>
  <b>Family:</b>
  <%= @guess.family %>
</p>

<p>
  <b>Common name:</b>
  <%= @guess.common_name %>
</p>

<p>
  <b>User:</b>
  <%= @guess.user_id %>
</p>

<p>
  <b>Image:</b>
  <%= @guess.image_id %>
</p>

<p>
  <b>Correct:</b>
  <%= @guess.correct %>
</p>


<%= link_to 'Edit', edit_guess_path(@guess) %> |
<%= link_to 'Back', guesses_path %>