config/routes.rb
MarineLifeIdApp::Application.routes.draw do
  resources :guesses
  resources :identifications

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :images do
   collection do
     get :practice
     get :identify
     get :explore
   end
    resources :identifications, except: [:index]
    resources :guesses, except: [:index]
  end

  get 'animals/family'
  get 'animals/common'

  resources :identifications, only: [:index]

  root :to => 'images#index'

end

app/models/identification.rb
class Identification < ActiveRecord::Base
  attr_accessible :common_name, :family, :image_id, :number, :suborder, :user_id
  belongs_to :image
  belongs_to :user

  #-----------------------------------------------------
    # Identification logic
  #-----------------------------------------------------
  
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  # GET /identifications
  # GET /identifications.json
  def index
    @identifications = Identification.all
    @image = Image.reviewed_images
    @identification = Identification.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @identifications }
    end
  end

  # GET /identifications/1
  # GET /identifications/1.json
  def show
    @identification = Identification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @identification }
    end
  end

  # GET /identifications/new
  # GET /identifications/new.json
  def new
    @identification = Identification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @identification }
    end
  end

  # GET /identifications/1/edit
  def edit
    @identification = Identification.find(params[:id])
  end

  # POST /identifications
  # POST /identifications.json
  def create
    @image = Image.find(params[:image_id])
    @identification = @image.identifications.new(params[:identification])
    @identification.user_id = current_user.id

    respond_to do |format|
      if @identification.save
        format.html { redirect_to images_path, notice: 'Identification was successfully created.' }
        format.json { render json: @identification, status: :created, location: @identification }
      else
        format.html { render action: "new" }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /identifications/1
  # PUT /identifications/1.json
  def update
    @identification = Identification.find(params[:id])

    respond_to do |format|
      if @identification.update_attributes(params[:identification])
        format.html { redirect_to @identification, notice: 'Identification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identifications/1
  # DELETE /identifications/1.json
  def destroy
    @identification = Identification.find(params[:id])
    @identification.destroy

    respond_to do |format|
      format.html { redirect_to identifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/identifications_helper.rb
module IdentificationsHelper
end

app/views/identifications/_form.html.erb
<%= form_for([@image, @identification]) do |f| %>
  <%= hidden_field_tag :image_id, @image.id %>
  <div class="field">
    <%= f.label :suborder %><br />
    <%= f.collection_select :suborder, Animal.select('DISTINCT(suborder)').order(:suborder), :suborder, :suborder, class: "dropdown-menu", include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :family %><br />
    <%= f.collection_select :family, [], :family, :family, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :common_name %><br />
    <%= f.collection_select :common_name, [], :id, :common_name, include_blank: true %>
  </div>
  <div class="actions" id="actions">
    <%= f.submit "identify!", class: "btn btn-default", id: "identify_button" %>
  </div>
<% end %>

app/views/identifications/edit.html.erb
<h1>Editing identification</h1>

<%= render 'form' %>

<%= link_to 'Show', @identification %> |
<%= link_to 'Back', identifications_path %>

app/views/identifications/index.html.erb
<h1>Listing identifications</h1>

<table>
  <tr>
    <th>Suborder</th>
    <th>Family</th>
    <th>Common name</th>
    <th>Number</th>
    <th>User</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @identifications.each do |identification| %>
  <tr>
    <td><%= identification.suborder %></td>
    <td><%= identification.family %></td>
    <td><%= identification.common_name %></td>
    <td><%= identification.number %></td>
    <td><%= identification.user_id %></td>
    <td><%= identification.image_id %></td>
    <td><%= link_to 'Show', identification %></td>
    <td><%= link_to 'Edit', edit_identification_path(identification) %></td>
    <td><%= link_to 'Destroy', identification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Identification', new_identification_path %>

app/views/identifications/new.html.erb
<h1>New identification</h1>

<%= render 'form' %>

<%= link_to 'Back', identifications_path %>

app/views/identifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Suborder:</b>
  <%= @identification.suborder %>
</p>

<p>
  <b>Family:</b>
  <%= @identification.family %>
</p>

<p>
  <b>Common name:</b>
  <%= @identification.common_name %>
</p>

<p>
  <b>Number:</b>
  <%= @identification.number %>
</p>

<p>
  <b>User:</b>
  <%= @identification.user_id %>
</p>

<p>
  <b>Image:</b>
  <%= @identification.image_id %>
</p>


<%= link_to 'Edit', edit_identification_path(@identification) %> |
<%= link_to 'Back', identifications_path %>